### ISSUE TITLE
if page refreshed alignment changed

### ISSUE THREAD

**Issue by rvsp** [Life-of-pi/FreshDesk-Hackathon#2]
https://github.com/Life-of-pi/FreshDesk-Hackathon/blob/955a21167bb798ab3b00f286a81b62b135c05bda/index3.html#L84

**content is not displayed, instead getting alert as success**

![image](https://user-images.githubusercontent.com/21954626/82739280-04205000-9d5c-11ea-9e89-905cc8fd85ff.png)

**Comment by Life-of-pi** [comment]
This issue after the page refresh is been resolved.
