### ISSUE TITLE
should shown clear message

### ISSUE THREAD

**Issue by rvsp** [Life-of-pi/FreshDesk-Hackathon#3]
https://github.com/Life-of-pi/FreshDesk-Hackathon/blob/955a21167bb798ab3b00f286a81b62b135c05bda/scripts/contactCreate.js#L15

if contact create form fields empty, could have shown better message

**Comment by Life-of-pi** [comment]
After creating a custom ticket and contact, a bootstrap alert has been added. This alert if not closed manually will disappear after 5 seconds.
